### ISSUE TITLE
URL Not fetching data

### ISSUE THREAD

**Issue by Lalrinfela** [zpelechova/covid-in#3]
Hi, Since yesterday, the url is not returning data. Any Help Please?

**Comment by zpelechova** [comment]
Hi, it should be working again, let us know if there are any issues, thanks! Zuzka

**Comment by Lalrinfela** [comment]
Hi, That was quick. Thank you so much, it's working. We use your API in our app if you want to check out - mCOVID19 (iOS and Android). Again, Thank You.

**Comment by zpelechova** [comment]
Thanks! It is always good to know that our data is being used!
