### ISSUE TITLE
Sign for Active cases New 

### ISSUE THREAD

**Issue by bhanuPrakashReddy2105** [zpelechova/covid-in#8]
In the response, we are getting activeNewCases without any sign (-ve or +ve). If the sign is specified as in regionData(newInfected) it would be easy to calculate today's cases

![image](https://user-images.githubusercontent.com/77768157/121139465-690af300-c856-11eb-9380-aff0fdfa99a4.png)

**Comment by zpelechova** [comment]
Hey, we moved the repo, but I fixed the issue anyway, should be ok no. please, check.

**Comment by bhanuPrakashReddy2105** [comment]
Thank you for the quick response. Can I get the new repo link?
